### Helper Functions
These functions are defined to validate the user input and can be used for convenience. Feel free to use them, but don't be discurged if some parts are not clear because they have not been covered yet.

* **int_input()** to prompt the user for integers.
* **float_input()** to prompt the user for real numbers.
* **date_input()** to prompt the user to enter a date.
* **integer_list_input()** to prompt the user to enter a list of numbers seperated by spaces.
# MAKE SURE TO RUN THIS CELL FIRST

In [0]:
import sys
from datetime import datetime
from datetime import date

def parsed_input(prompt, parser):
  """
  Keeps prompting the user to enter a value until the value is accepted by
  the parser. Returns the parsed value.
  
  Parameters
  ----------
  prompt: str
    The message that will be shown to the user.
  parser: callable
    A function that takes a string and returns a value of the desired type,
    or raises an exception if the input string is not in the expected format.
    
  Returns
  -------
  parsed_value: obj
    A value of the type returned by the parser function.
  """
  while True:
    try:
      s = parser(input(prompt))
      return s
    except ValueError as e:
      print("ValueError: ", e, file=sys.stderr)

def int_input(prompt):
  return parsed_input(prompt, int)

def float_input(prompt):
  return parsed_input(prompt, float)

def date_input(prompt,date_format='%d/%m/%Y'):
  return parsed_input(prompt, lambda x: datetime.strptime(x, date_format))


def parse_integer_list(string):
  # NOTE: you can also use regular expressions instead of this.
  numbers = string.split()
  numbers = [int(x) for x in numbers] # change from strings to integers,
                                      # lookup List Comprehensions in Python
                                      # if interested in knowing how this line works
  return numbers

def integer_list_input(prompt):
  return parsed_input(prompt, parse_integer_list)

# Question 1 [Sets intersection]
**Write a Python program that reads two integer number sets from the user and then prints their
intersection.**

In [2]:

set1 = set(integer_list_input("Enter set 1 numbers: "))
set2 = set(integer_list_input("Enter set 2 numbers: "))

print("Intersection = ", set1 & set2)

Enter set 1 numbers: 1 2 3 4 7 8 9
Enter set 2 numbers: 0 1 2 5 8
Intersection =  {8, 1, 2}

# Question 2 [Largest number]
**Write a Python program to read a list of integer numbers from the user and then:**
* Print the largest number in the list
* Print the smallest number in the list

In [3]:
numbers = integer_list_input("Enter numbers: ")

numbers.sort()

print("Smallest number", numbers[0])
print("Largest number:", numbers[-1])

Enter numbers: 3 4 1 -32 12 2434 1 0 0
Smallest number -32
Largest number: 2434

# Question 3 [Remove even numbers]
**Write a Python program to read a list of integer numbers from the user. Then create a new list with even numbers removed from the old list.**

In [4]:
numbers = integer_list_input("Enter numbers: ")
odd_numbers = []

for x in numbers:
  if x % 2 != 0:
    odd_numbers.append(x)
print("New list:", odd_numbers)

Enter numbers: 23 11 53 58 21 11 10
New list: [23, 11, 53, 21, 11]

# Question 4 [Class average]
**Write a Python program to read students marks from the user and then prints the class average. Your program must continue reading marks from the user until the user enter -1 to indicate the end of marks.**

In [5]:
marks = []

while True:
  n = float_input("Enter a student mark: ")
  if n == -1:
    break
  marks.append(n)

print("Class average:", round(sum(marks)/len(marks), 2))

Enter a student mark: 90
Enter a student mark: 24
Enter a student mark: 80
Enter a student mark: 98
Enter a student mark: 76
Enter a student mark: -1
Class average: 73.6

# Question 5 [Student marks storage]
**Write a Python program to read five students marks and store them in a dictionary. Dictionary key should be the student id, and the value associated is the mark. Sort the dictionary based on key, and then print the dictionary.**

In [6]:
student_ids = ['123546', '657643', '176395', '381638', '638254']
marks_dict = {}

for i in range(5):
  n = float_input("Enter student %s mark: " % student_ids[i])
  marks_dict[student_ids[i]] = n

print("Student id\tMark")
for key in sorted(marks_dict):
  print(key, marks_dict[key],sep='\t\t')

# # ALTERNATIVE
# import operator
# marks_dict = sorted(marks_dict.items(), key=operator.itemgetter(0))
# print(marks_dict)

Enter student 123546 mark: 76
Enter student 657643 mark: 98
Enter student 176395 mark: 36
Enter student 381638 mark: 89
Enter student 638254 mark: 70
Student id	Mark
123546		76.0
176395		36.0
381638		89.0
638254		70.0
657643		98.0